const students = [
  {
    id: 1,
    first_name: "Louisette",
    last_name: "Archibould",
    email: "larchibould0@newyorker.com",
    gender: "Female",
    ip_address: "147.208.209.242",
  },
  {
    id: 2,
    first_name: "Pattie",
    last_name: "Eberst",
    email: "peberst1@sakura.ne.jp",
    gender: "Female",
    ip_address: "131.250.123.51",
  },
  {
    id: 3,
    first_name: "Duff",
    last_name: "Kevlin",
    email: "dkevlin2@list-manage.com",
    gender: "Non-binary",
    ip_address: "57.151.210.139",
  },
  {
    id: 4,
    first_name: "Franchot",
    last_name: "Priddle",
    email: "fpriddle3@nydailynews.com",
    gender: "Male",
    ip_address: "52.30.168.250",
  },
  {
    id: 5,
    first_name: "Tadd",
    last_name: "Royce",
    email: "troyce4@archive.org",
    gender: "Male",
    ip_address: "183.186.141.224",
  },
  {
    id: 6,
    first_name: "Dorita",
    last_name: "Fairbourn",
    email: "dfairbourn5@wikimedia.org",
    gender: "Female",
    ip_address: "132.143.9.148",
  },
  {
    id: 7,
    first_name: "Ema",
    last_name: "Cheshire",
    email: "echeshire6@blogspot.com",
    gender: "Female",
    ip_address: "142.89.68.150",
  },
  {
    id: 8,
    first_name: "Bernie",
    last_name: "Golt",
    email: "bgolt7@mtv.com",
    gender: "Male",
    ip_address: "62.164.19.83",
  },
  {
    id: 9,
    first_name: "Arnuad",
    last_name: "Sergant",
    email: "asergant8@reference.com",
    gender: "Male",
    ip_address: "56.251.29.239",
  },
  {
    id: 10,
    first_name: "Hamil",
    last_name: "O'Connell",
    email: "hoconnell9@state.gov",
    gender: "Male",
    ip_address: "48.32.12.216",
  },
];
module.exports=students