var studentArray = [
  {
    id: 1,
    first_name: "Blane",
    last_name: "Gilbey",
    email: "bgilbey0@booking.com",
    gender: "Male",
    ip_address: "161.255.48.99",
  },
  {
    id: 2,
    first_name: "Melodie",
    last_name: "Rounsefull",
    email: "mrounsefull1@g.co",
    gender: "Female",
    ip_address: "227.163.57.133",
  },
  {
    id: 3,
    first_name: "Den",
    last_name: "Langthorn",
    email: "dlangthorn2@yandex.ru",
    gender: "Male",
    ip_address: "174.141.181.88",
  },
  {
    id: 4,
    first_name: "Michael",
    last_name: "Sutter",
    email: "msutter3@com.com",
    gender: "Male",
    ip_address: "15.48.149.148",
  },
  {
    id: 5,
    first_name: "Nisse",
    last_name: "Stoggell",
    email: "nstoggell4@moonfruit.com",
    gender: "Female",
    ip_address: "172.42.84.25",
  },
  {
    id: 6,
    first_name: "Putnam",
    last_name: "Redmell",
    email: "predmell5@networkadvertising.org",
    gender: "Male",
    ip_address: "119.187.220.89",
  },
  {
    id: 7,
    first_name: "Cchaddie",
    last_name: "Ashmole",
    email: "cashmole6@mtv.com",
    gender: "Male",
    ip_address: "15.180.15.153",
  },
  {
    id: 8,
    first_name: "Boony",
    last_name: "Norssister",
    email: "bnorssister7@ameblo.jp",
    gender: "Genderqueer",
    ip_address: "16.46.112.122",
  },
  {
    id: 9,
    first_name: "Jody",
    last_name: "Davydoch",
    email: "jdavydoch8@livejournal.com",
    gender: "Female",
    ip_address: "92.222.107.102",
  },
  {
    id: 10,
    first_name: "Rutledge",
    last_name: "Jeacocke",
    email: "rjeacocke9@edublogs.org",
    gender: "Male",
    ip_address: "160.182.5.206",
  }
]
module.exports=studentArray;